title: Welcome to the Test
author: It's just Jae
description: > # this means to ignore newlines until "baseurl:"
This is a space being used to help me become more acclimated with GitHub. Not much else to see here.

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
